/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-07-03 06:31:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import Models.Program;
import Utilities.ProgramUtil;

public final class addProgramToInst_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1498989697559L));
    _jspx_dependants.put("jar:file:/C:/Users/Joanna%20Lau/Desktop/THESIS/paws/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PAWS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Models.Program");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("Utilities.ProgramUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("    <script src='js/jquery.min.js'></script>\r\n");
      out.write("    <script src='js/jquery-ui.min.js'></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("        <title> PAASCU - Accreditation Schedule Manager </title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("        <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/vendor.css\">\r\n");
      out.write("        <!-- Theme initialization -->\r\n");
      out.write("        <script>\r\n");
      out.write("            var themeSettings = (localStorage.getItem('themeSettings')) ? JSON.parse(localStorage.getItem('themeSettings')) :\r\n");
      out.write("            {};\r\n");
      out.write("            var themeName = themeSettings.themeName || '';\r\n");
      out.write("            if (themeName)\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app-' + themeName + '.css\">');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app.css\">');\r\n");
      out.write("            }\r\n");
      out.write("        </script><link href='fullcalendar.css' rel='stylesheet' />\r\n");
      out.write("        \r\n");
      out.write("<link href='calendar/fullcalendar.print.css' rel='stylesheet' media='print' />\r\n");
      out.write("<script src='calendar/lib/moment.min.js'></script>\r\n");
      out.write("<script src='calendar/fullcalendar.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("function addAlert(asd){\r\n");
      out.write("\t$('#section').append('<div class=\"alert alert-success\"><a href=\"#\" class=\"close\" data-dismiss=\"alert\" aria-label=\"close\">&times;</a><strong>Success!</strong> Successfully added survey called: '+asd +'.</div> <br>');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function addProgram(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar strUser = $('#program option:selected').text();\r\n");
      out.write("\t\r\n");
      out.write("\tvar x = document.createElement(\"LI\");\r\n");
      out.write("\t\r\n");
      out.write("\tx.innerHTML = \"\" + strUser + \"\";\r\n");
      out.write("\tx.classList.add(\"list-group-item\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar b = document.createElement(\"BUTTON\");\r\n");
      out.write("\tb.type=\"button\";\r\n");
      out.write("\tb.innerHTML = \"<i class='fa fa-trash-o'></i> Delete\";\r\n");
      out.write("\tb.classList.add(\"btn\");\r\n");
      out.write("\tb.classList.add(\"btn-link\");\r\n");
      out.write("\tb.classList.add(\"btn-sm\");\r\n");
      out.write("\tb.onclick = function (){\r\n");
      out.write("\t\tthis.parentNode.parentNode.removeChild(this.parentNode);\r\n");
      out.write("\t}\r\n");
      out.write("\tb.style = \"float:right;\";\r\n");
      out.write("\t\r\n");
      out.write("\t$('#addedList').append(x);\r\n");
      out.write("\tx.appendChild(b);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar lal = document.getElementById(\"added\");\r\n");
      out.write("\tlal.scrollTop = lal.scrollHeight;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("function changeDetails(){\r\n");
      out.write("\t$(\"#progProponents\").className = \"progress-bar progress-bar-success progress-bar-striped\";\r\n");
      out.write("\t$(\"#progDetails\").className = \"progress-bar progress-bar-success\";\r\n");
      out.write("\t$(\"#progSure\").className = \"progress-bar progress-bar-success\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-family: \"Lucida Grande\",Helvetica,Arial,Verdana,sans-serif;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#calendar {\r\n");
      out.write("\t\tmax-width: 900px;\r\n");
      out.write("\t\tmargin: -35px auto;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("background: rgba(255,255,255,1);\r\n");
      out.write("background: -moz-linear-gradient(45deg, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("background: -webkit-gradient(left bottom, right top, color-stop(0%, rgba(255,255,255,1)), color-stop(47%, rgba(246,246,246,1)), color-stop(100%, rgba(237,237,237,1)));\r\n");
      out.write("background: -webkit-linear-gradient(45deg, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("background: -o-linear-gradient(45deg, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("background: -ms-linear-gradient(45deg, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("background: linear-gradient(45deg, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ededed', GradientType=1 );\t\r\n");
      out.write("\t box-shadow: 1px 2px 5px #C0C0C0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.fc-day-number{\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#bg{\r\n");
      out.write("\theight: 640px;\r\n");
      out.write("\tposition:fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#progItem{\r\n");
      out.write("\t\r\n");
      out.write("    border: 1px solid #ececec;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("\tpadding: 5px 5px 5px 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("    \t \r\n");
      out.write("        <div class=\"main-wrapper\">\r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("        \t\t\t\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("\r\n");
      out.write("  \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <div class=\"app\" id=\"app\">\r\n");
      out.write("                \r\n");
      out.write("                <aside class=\"sidebar\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                    <div class=\"sidebar-container\">\r\n");
      out.write("                    \t\r\n");
      out.write("                        <div class=\"sidebar-header\">\r\n");
      out.write("                            <div class=\"brand\">\r\n");
      out.write("                                <div class=\"logo\"style=\"width:100%\"> <img src=\"assets/logoicon.png\" style=\"width:90%;height:170%; top:-5%;left:-5%; opacity:1\"> </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <nav class=\"menu\">\r\n");
      out.write("                            <ul class=\"nav metismenu\" id=\"sidebar-menu\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"index.html\"> <i class=\"fa fa-home\"></i> Dashboard </a>\r\n");
      out.write("                               <li>\r\n");
      out.write("                                    <a href=\"survey.jsp\"> <i class=\"fa fa-table\"></i> Survey Schedule </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("                                </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("                                    <a href=\"addSurvey.jsp\"> <i class=\"fa fa-pencil-square-o\"></i> Add New Survey </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li  class=\"active\">\r\n");
      out.write("                                    <a href=\"#demo\" data-toggle=\"collapse\"> <i class=\"fa fa-file-text-o\"></i> Database <i class=\"fa arrow\"></i> </a>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <ul id=\"demo\" class=\"collapse\">\r\n");
      out.write("                                  \r\n");
      out.write("                                        <li> <a href=\"Accreditors\">\r\n");
      out.write("    \t\t\t\t\t\t\t\tAccreditors\r\n");
      out.write("    \t\t\t\t\t\t\t</a> </li>\r\n");
      out.write("                                        <li class=\"active\"> <a href=\"Institutions\">\r\n");
      out.write("    \t\t\t\t\t\t\t\tInstitutions\r\n");
      out.write("    \t\t\t\t\t\t\t</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li> <a href=\"SchoolSystems\">\r\n");
      out.write("    \t\t\t\t\t\t\t                School Systems\r\n");
      out.write("    \t\t\t\t\t\t\t</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li> <a href=\"Programs\">\r\n");
      out.write("    \t\t\t\t\t\t\t\tDisciplines </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("                                 \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"#demo3\" data-toggle=\"collapse\"> <i class=\"fa fa-bar-chart\"></i> Reports <i class=\"fa arrow\"></i> </a><ul id=\"demo3\" class=\"collapse\"><li> <a href=\"reportGA.html\">GA Awardees</a> </li><li> <a href=\"reportHistory.html\">History</a> </li></ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t </li>\r\n");
      out.write("                                \r\n");
      out.write("                               \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <footer class=\"sidebar-footer\">\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                </aside>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <div class=\"sidebar-overlay\" id=\"sidebar-overlay\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <article class=\"content dashboard-page\">\r\n");
      out.write("\t\t\t\t <div class=\"title-block\">\r\n");
      out.write("                        <h3 class=\"title\" style=\"float:left;\">\r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ViewInstitution?institutionID=");
      out.print(request.getParameter("ID") );
      out.write("\"> <em class=\"fa fa-arrow-circle-left\"></em> ");
      out.print(request.getParameter("Name") );
      out.write("</a> \r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t     </div>\r\n");
      out.write("\t\t\t\t<section class=\"section\" id=\"section2\"> \r\n");
      out.write("    \t\t\t\t\t<form method=\"POST\" action=\"AddProgramToInst\" class=\"form\">\r\n");
      out.write("    \t\t\t\t\t<div id=\"add\" style=\"float:left; width: 100%; height: 460px;\" class=\"card sameheight-item\">\r\n");
      out.write("    \t\t\t\t\t<div class=\"card-block\">\r\n");
      out.write("    \t\t\t\t\t<h3>Select General Field of Discipline</h3>\r\n");
      out.write("    \t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("  \t\t\t\t\t\t<select name = \"general\" class=\"form-control\" id=\"program\">\r\n");
      out.write("  \t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t");
ArrayList<Program> programs = new ArrayList<Program>();
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t");
ProgramUtil progUtil = new ProgramUtil();
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t");
programs = progUtil.getPrograms(); 
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t<option><i></i></option>\r\n");
      out.write("  \t\t\t\t\t\t\t");
for(Program temp: programs){ 
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t\t<option value=");
      out.print(temp.getProgramID());
      out.write(' ');
      out.write('>');
      out.print(temp.getName() );
      out.write("</option>\r\n");
      out.write("    \t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("  \t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label>Specific Program Name: </label><input type=\"text\" style=\"width: 100%;\" placeholder=\"Enter Specific Name of the Program\" class=\"form-control underlined\" name=\"specific\" id=\"surveyName\">\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<input type=\"hidden\" name=\"instID\" value=");
      out.print(request.getParameter("ID") );
      out.write(">\r\n");
      out.write("  \t\t\t\t\t\t<br>\r\n");
      out.write("  \t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\"  style=\"float:right;\">\r\n");
      out.write("  \t\t\t\t\t\t<em class=\"fa fa-floppy-o\"></em> Save Program\r\n");
      out.write("  \t\t\t\t\t\t</button>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("        \t\t\t</form>\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t</section>\r\n");
      out.write("        \t\t\t<hr>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t </article>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("               \r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("        \t\t  \r\n");
      out.write("        <!-- Reference block for JS -->\r\n");
      out.write("        <div class=\"ref\" id=\"ref\">\r\n");
      out.write("            <div class=\"color-primary\"></div>\r\n");
      out.write("            <div class=\"chart\">\r\n");
      out.write("                <div class=\"color-primary\"></div>\r\n");
      out.write("                <div class=\"color-secondary\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       </div></div>\r\n");
      out.write("        <script src=\"js/app.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
