/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-07-22 18:04:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editNews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Keith/Desktop/paws/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PAWS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500738660093L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Edit News</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("        <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/vendor.css\">\r\n");
      out.write("        <!-- Theme initialization -->\r\n");
      out.write("        <script>\r\n");
      out.write("            var themeSettings = (localStorage.getItem('themeSettings')) ? JSON.parse(localStorage.getItem('themeSettings')) :\r\n");
      out.write("            {};\r\n");
      out.write("            var themeName = themeSettings.themeName || '';\r\n");
      out.write("            if (themeName)\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app-' + themeName + '.css\">');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app.css\">');\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("\t\t\r\n");
      out.write("<script src=\"calendar/fullcalendar.js\"></script>\r\n");
      out.write("    \t<script src=\"calendar/fullcalendar.min.js\"></script>\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("  \r\n");
      out.write("      <script type=\"text/javascript\" src=\"js/jspdf.min.js\"></script>\r\n");
      out.write("      <script src=\"js/jquery-2.1.3.min.js\"></script>\r\n");
      out.write("      <script type=\"text/javascript\" src=\"js/html2canvas.min.js\"></script>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/stylestest.css\"/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t.container{\r\n");
      out.write("\t\twidth: 110%;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tz-index:-1;\r\n");
      out.write("\t\tmargin-left:-15px;\r\n");
      out.write("}\r\n");
      out.write("\t#bgvid{\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\ttop:-400px;\r\n");
      out.write("\t\tmargin-top:0px;\r\n");
      out.write("\t\twidth:110%\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-family: \"Lucida Grande\",Helvetica,Arial,Verdana,sans-serif;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#calendar {\r\n");
      out.write("\t\tmax-width: 900px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t#bg{\r\n");
      out.write("\t\theight: 640px;\r\n");
      out.write("\t\tposition:fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#main{\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\ttop:-290px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pnum_danger,#pnum_info,#pnum_warning,#pnum_primary{\r\n");
      out.write("\t\tfont-size:75px; \r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\t margin-left: -2px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tline-height:85px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pnum_danger{\r\n");
      out.write("\tcolor:#5c5c5c;\t\r\n");
      out.write("\ttransition: all 0.5s ease;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\t#pnum_danger:hover{\r\n");
      out.write("\t\tcolor:#ff2b2b;\t\r\n");
      out.write("\t\tfont-size:100px;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t#pnum_warning{\r\n");
      out.write("\tcolor:#5c5c5c;\t\r\n");
      out.write("\ttransition: all 0.5s ease;\r\n");
      out.write("\t}\t#pnum_warning:hover{\r\n");
      out.write("\t\tfont-size:100px;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\tcolor:#fe8832;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#pnum_info{\r\n");
      out.write("\tcolor:#5c5c5c;\t\r\n");
      out.write("\ttransition: all 0.5s ease;\r\n");
      out.write("\t}\t#pnum_info:hover{\r\n");
      out.write("\t\tcolor:#5ecdf3;\r\n");
      out.write("\t\tfont-size:100px;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pnum_primary{\r\n");
      out.write("\tcolor:#5c5c5c;\t\r\n");
      out.write("\ttransition: all 0.5s ease;\r\n");
      out.write("\t}\t#pnum_primary:hover{\r\n");
      out.write("\t\tcolor:#85CE36;\r\n");
      out.write("\t\tfont-size:100px;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#psub{\r\n");
      out.write("\t\tfont-size:17px; \r\n");
      out.write("\t\tcolor:#bcbcbc;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin-top: 6px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tline-height:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#bc {\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#bc:hover { \r\n");
      out.write("\t\tcolor:#85CE36;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#welcome{\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\ttop:-110px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tleft:40px;\r\n");
      out.write("\t\tfont-family:Existence-Light;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.h1{\r\n");
      out.write("\t\tfont-size:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t@font-face {\r\n");
      out.write("\t\tfont-family: Existence-Light;\r\n");
      out.write("\t\tsrc: url(fonts/Roboto-Thin.ttf);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t#notifcard{\r\n");
      out.write("\t\t-webkit-box-shadow: 0px 1px 5px 0px rgba(50, 50, 50, 0.58);\r\n");
      out.write("-moz-box-shadow:    0px 1px 5px 0px rgba(50, 50, 50, 0.58);\r\n");
      out.write("box-shadow:         0px 1px 5px 0px rgba(50, 50, 50, 0.58);\r\n");
      out.write("\t\twidth:87%;\r\n");
      out.write("\t\tleft:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#maincard{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\tpadding:0px;\r\n");
      out.write("\t\tbackground-color: #ffffff;\r\n");
      out.write("\t\ttop:-50px;\r\n");
      out.write("\t\tmargin-bottom: 10px;\r\n");
      out.write("\t\tmargin-top: 0px;\r\n");
      out.write("\t\theight:700px;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t   \r\n");
      out.write("\t\t-webkit-box-shadow: 0px 9px 24px 0px rgba(0,0,0,0.75);\r\n");
      out.write("\t\t-moz-box-shadow: 0px 9px 24px 0px rgba(0,0,0,0.75);\r\n");
      out.write("\t\tbox-shadow: 0px 9px 24px 0px rgba(0,0,0,0.75);\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"main-wrapper\" style=\"z-index:1;\">\r\n");
      out.write("            <div class=\"app\" id=\"app\">\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("              \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t<video poster=\"assets/banner.jpg\" id=\"bgvid\"  playsinline autoplay muted loop>\r\n");
      out.write("  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the \"Pause\" button  -->\r\n");
      out.write("\r\n");
      out.write("<source src=\"assets/vid.mp4\" type=\"video/mp4\">\r\n");
      out.write("</video>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("          \r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("                <article class=\"content dashboard-page\" >\r\n");
      out.write("                    <section class=\"section\" style=\"position: relative; top:-130px;\">\r\n");
      out.write("                      \r\n");
      out.write("\t\t\t\t\t <div class=\"title-block\">\r\n");
      out.write("                        <h6 class=\"title\" style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\tEdit News\r\n");
      out.write("\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                  \r\n");
      out.write("    \r\n");
      out.write(" <div id=\"sample\">\r\n");
      out.write(" <script type=\"text/javascript\" src=\"js/nicEdit.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("//<![CDATA[\r\n");
      out.write("  bkLib.onDomLoaded(function() {\r\n");
      out.write("    \r\n");
      out.write("       new nicEditor({buttonList : ['bold','italic','underline','strikeThrough','link']}).panelInstance('newsBody');\r\n");
      out.write("\r\n");
      out.write("  });\r\n");
      out.write("  //]]>\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("  \r\n");
      out.write("  <form method=\"post\" action=\"EditNews\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <label>News Title: </label>&nbsp;&nbsp;<input id=\"newsTitle\" name=\"title\" value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\"><br><br>\r\n");
      out.write("  <label>News Content: </label><br>\r\n");
      out.write("  <textarea rows=\"25\" cols=\"200\" id=\"newsBody\" name=\"content\">\r\n");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</textarea>\r\n");
      out.write(" <br>\r\n");
      out.write("<label>News Image (Optional): </label>   &nbsp;&nbsp;  \r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    <input type=\"file\"><br><br>\r\n");
      out.write("     \r\n");
      out.write("     <button onclick=\"printText();\" type=\"submit\" value=\"Submit\">Update News</button>\r\n");
      out.write("  \r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("    <!-- <input type=\"button\" id=\"button\" value=\"Submit\"/> -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </form>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("</div>    \r\n");
      out.write("</section></article></div></div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write(" <!-- Reference block for JS -->\r\n");
      out.write("        <div class=\"ref\" id=\"ref\">\r\n");
      out.write("            <div class=\"color-primary\"></div>\r\n");
      out.write("            <div class=\"chart\">\r\n");
      out.write("                <div class=\"color-primary\"></div>\r\n");
      out.write("                <div class=\"color-secondary\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"js/vendor.js\"></script>\r\n");
      out.write("        <script src=\"js/app.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    function printText(){\r\n");
      out.write("        \r\n");
      out.write("     var nicE = new nicEditors.findEditor('newsBody');\r\n");
      out.write("     var x = nicE.getContent();\r\n");
      out.write("        \r\n");
      out.write("        alert(x);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /editNews.jsp(292,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("news");
      // /editNews.jsp(292,4) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("session");
      // /editNews.jsp(292,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/editNews.jsp(292,4) '${News}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${News}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /editNews.jsp(293,83) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getTitle()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /editNews.jsp(296,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.getContent()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
