/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-07-03 06:27:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Models.ProgramSurvey;
import java.util.*;

public final class institutionProgramProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1498989697559L));
    _jspx_dependants.put("jar:file:/C:/Users/Joanna%20Lau/Desktop/THESIS/paws/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PAWS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Models.ProgramSurvey");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("        <title> PAASCU - Accreditation Schedule Manager </title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\t\t  <!-- IMPORTS -->\r\n");
      out.write("<!--     <script src='js/jquery.min.js'></script> -->\r\n");
      out.write("<!--     <script src='js/jquery-ui.min.js'></script> -->\r\n");
      out.write("<!--     <link rel=\"stylesheet\" href=\"css/bootstrap.css\"> -->\r\n");
      out.write("<!--     <script src=\"js/bootstrap.min.js\"></script> -->\r\n");
      out.write("<!--     <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\"> -->\r\n");
      out.write("<!--     <link rel=\"stylesheet\" href=\"css/vendor.css\"> -->\r\n");
      out.write("<!--     <link href='fullcalendar.css' rel='stylesheet' /> -->\r\n");
      out.write("<!--     <link href='calendar/fullcalendar.print.css' rel='stylesheet' media='print' /> -->\r\n");
      out.write("<!-- \t<script src='calendar/lib/moment.min.js'></script> -->\r\n");
      out.write("<!-- \t<script src='calendar/fullcalendar.min.js'></script> -->\r\n");
      out.write("<!-- \t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"> -->\r\n");
      out.write("<!-- \t<link rel=\"stylesheet\" type=\"text/css\" href=\" css/dataTables.bootstrap.min.css\"> -->\r\n");
      out.write("<!-- \t<script src=\"js/jquery.dataTables.min.js\"></script> -->\r\n");
      out.write("<!-- \t<script src=\"js/dataTables.bootstrap.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/vendor.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\" css/dataTables.bootstrap.min.css\">\r\n");
      out.write("\t<link href=\"css/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\t\r\n");
      out.write("\t<link href=\"css/dataTables.jqueryui.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\t\r\n");
      out.write("\t<link href=\"css/jquery.dataTables.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\t\r\n");
      out.write("\t<link href=\"css/buttons.dataTables.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src='js/jquery.min.js'></script>\r\n");
      out.write("    <script src='js/jquery-ui.min.js'></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/dataTables.jqueryui.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/buttons.print.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jszip.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/pdfmake.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/buttons.html5.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/vfs_fonts.js\"></script>\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- END IMPORTS -->\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/app.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/vendor.css\">\r\n");
      out.write("        <!-- Theme initialization -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("     $('#smarttable').DataTable( {\r\n");
      out.write("        dom: 'Bfrtip',\r\n");
      out.write("        \r\n");
      out.write("        \"columnDefs\":[{\r\n");
      out.write("        \t\"width\":\"20%\",\"targets\": 0,1,2,3,4 }\r\n");
      out.write("        }],\r\n");
      out.write("    \tbuttons: [\r\n");
      out.write("                  {\r\n");
      out.write("                \t  extend: 'pdfHtml5',\r\n");
      out.write("                \t  title: \"Survey History\",\r\n");
      out.write("                \t  download: 'open',\r\n");
      out.write("                \t  message: \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("                \t  customize: function ( doc ) {\r\n");
      out.write("                          alert(JSON.stringify(doc.content[1].style));\r\n");
      out.write("                          var wew = { text: '");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("', style: '{alignment:\"center\", fontSize:22, bold:true}' };\r\n");
      out.write("                          doc.content.push(wew);\r\n");
      out.write("                          doc.content[1].style = [\"message\", \"{alignment:'center', fontSize:22, bold:true}\"];\r\n");
      out.write("                          alert(JSON.stringify(doc.content[1].style));\r\n");
      out.write("\r\n");
      out.write("                      }\r\n");
      out.write("                  },\r\n");
      out.write("                  {\r\n");
      out.write("                \t  extend: 'excelHtml5',\r\n");
      out.write("                \t  title: \"Survey History\",\r\n");
      out.write("                \t  message: \"Putangina\"\r\n");
      out.write("                  }\r\n");
      out.write("                  \r\n");
      out.write("        ]\r\n");
      out.write("    } );\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("} );\r\n");
      out.write("$.fn.dataTable.ext.errMode = 'none';\r\n");
      out.write("\r\n");
      out.write("            var themeSettings = (localStorage.getItem('themeSettings')) ? JSON.parse(localStorage.getItem('themeSettings')) :\r\n");
      out.write("            {};\r\n");
      out.write("            var themeName = themeSettings.themeName || '';\r\n");
      out.write("            if (themeName)\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app-' + themeName + '.css\">');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app.css\">');\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#contenthole{\r\n");
      out.write("\t\t-webkit-box-shadow: 0px 4px 13px -4px rgba(0,0,0,0.5);\r\n");
      out.write("\t\t-moz-box-shadow: 0px 4px 13px -4px rgba(0,0,0,0.5);\r\n");
      out.write("\t\tbox-shadow: 0px 4px 13px -4px rgba(0,0,0,0.5);\r\n");
      out.write("\t\tpadding:15px;\r\n");
      out.write("\t\tbackground-color: #f8f8f8;\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t#smarttable th, #smarttable td {\t\t\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\ttext-overflow: ellipsis;\r\n");
      out.write("\t\twhite-space: nowrap;\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#smarttable th{\r\n");
      out.write("\t\tbackground-color:#85CE36; !important\r\n");
      out.write("\t\tcolor:#3c4731;\r\n");
      out.write("\t\tfont-size:110%;\t\t}\r\n");
      out.write("\r\n");
      out.write("\t#smarttable td{\r\n");
      out.write("\t\tpadding:15px;\r\n");
      out.write("\t\tpadding-left:10px;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\tcolor:#3c4731;\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t#smarttable tr:nth-child(even){\r\n");
      out.write("\t\tbackground-color:#e6f2da;}\r\n");
      out.write("\t\r\n");
      out.write("\t.container{\r\n");
      out.write("\t\twidth: 125%;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\theight: 130px;\r\n");
      out.write("\t\tz-index:-1;\r\n");
      out.write("\t\tmargin-left:-15px;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#smarttable tr:hover {\r\n");
      out.write("\t\tbackground: rgba(255,255,255,1);\r\n");
      out.write("\t\tbackground: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(255,255,255,1)), color-stop(47%, rgba(246,246,246,1)), color-stop(100%, rgba(237,237,237,1)));\r\n");
      out.write("\t\tbackground: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: -o-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: -ms-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: linear-gradient(to bottom, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ededed', GradientType=0 );\r\n");
      out.write("\r\n");
      out.write("\t\t-webkit-box-shadow: inset 0px 1px 5px 0px rgba(0,0,0,0.49);\r\n");
      out.write("\t\t-moz-box-shadow: inset 0px 1px 5px 0px rgba(0,0,0,0.49);\r\n");
      out.write("\t\tbox-shadow: inset 0px 1px 5px 0px rgba(0,0,0,0.49);\r\n");
      out.write("\t\tcursor: pointer;}\r\n");
      out.write("\r\n");
      out.write("\t#bgvid{\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\ttop:-400px;\r\n");
      out.write("\t\tmargin-top:0px;\r\n");
      out.write("\t\twidth:115%\t}\r\n");
      out.write("\r\n");
      out.write("\tbody {\t\t\r\n");
      out.write("\t\tfont-family: \"Lucida Grande\",Helvetica,Arial,Verdana,sans-serif;\r\n");
      out.write("\t\tfont-size: 14px;\t}\r\n");
      out.write("\r\n");
      out.write("\t#calendar {\r\n");
      out.write("\t\tmax-width: 900px;\r\n");
      out.write("\t\tmargin: 0 auto;\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#bg{\r\n");
      out.write("\t\theight: 640px;\r\n");
      out.write("\t\tposition:fixed;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#main{\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\ttop:-290px;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pnum_danger,#pnum_info,#pnum_warning,#pnum_primary{\r\n");
      out.write("\t\tfont-size:75px; \r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin-left: -2px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tline-height:85px;\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#pnum_danger{\r\n");
      out.write("\tcolor:#ff2b2b;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pnum_warning{\r\n");
      out.write("\t\tcolor:#fe8832;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pnum_info{\r\n");
      out.write("\t\tcolor:#5ecdf3;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pnum_primary{\r\n");
      out.write("\t\tcolor:#85CE36;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#psub{\r\n");
      out.write("\t\tfont-size:17px; \r\n");
      out.write("\t\tcolor:#bcbcbc;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin-top: 6px;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tline-height:20px;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#bc {\r\n");
      out.write("\t\tcolor:white;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#bc:hover { \r\n");
      out.write("\t\tcolor:#85CE36;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#welcome{\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\ttop:-65px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tleft:20px;\r\n");
      out.write("\t\tfont-family:Existence-Light;\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t.h1{\r\n");
      out.write("\t\tfont-size:100%;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t@font-face {\r\n");
      out.write("\t\tfont-family: Existence-Light;\r\n");
      out.write("\t\tsrc: url(fonts/Roboto-Thin.ttf);}\r\n");
      out.write("\t\t\r\n");
      out.write("\t@font-face {\r\n");
      out.write("\t\tfont-family: Existence-Medium;\r\n");
      out.write("\t\tsrc: url(fonts/Roboto-Regular.ttf);\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t#notifcard{\r\n");
      out.write("\t\t-webkit-box-shadow: 0px 1px 5px 0px rgba(50, 50, 50, 0.58);\r\n");
      out.write("\t\t-moz-box-shadow:    0px 1px 5px 0px rgba(50, 50, 50, 0.58);\r\n");
      out.write("\t\tbox-shadow:         0px 1px 5px 0px rgba(50, 50, 50, 0.58);\r\n");
      out.write("\t\twidth:87%;\r\n");
      out.write("\t\tleft:15px;\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#customheader{\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\ttop:124px;  \r\n");
      out.write("\t\theight:7px; \r\n");
      out.write("\t\t-webkit-box-shadow: 0px 2px 6px 2px rgba(50, 50, 50, 0.58);\r\n");
      out.write("\t\t-moz-box-shadow:    0px 2px 6px 2px rgba(50, 50, 50, 0.58);\r\n");
      out.write("\t\tbox-shadow:         0px 2px 7px 2px rgba(50, 50, 50, 0.58); \r\n");
      out.write("\t\tfont-family:Existence-Medium;\r\n");
      out.write("\t\tcolor:#f4f4f4;\r\n");
      out.write("\t\tfont-size:90%;\r\n");
      out.write("/* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#eaeaea+0,eae8e8+49,dadada+51,b2b0b0+100 */\r\n");
      out.write("background: rgb(234,234,234); /* Old browsers */\r\n");
      out.write("background: -moz-linear-gradient(top,  rgba(234,234,234,1) 0%, rgba(234,232,232,1) 49%, rgba(218,218,218,1) 51%, rgba(178,176,176,1) 100%); /* FF3.6-15 */\r\n");
      out.write("background: -webkit-linear-gradient(top,  rgba(234,234,234,1) 0%,rgba(234,232,232,1) 49%,rgba(218,218,218,1) 51%,rgba(178,176,176,1) 100%); /* Chrome10-25,Safari5.1-6 */\r\n");
      out.write("background: linear-gradient(to bottom,  rgba(234,234,234,1) 0%,rgba(234,232,232,1) 49%,rgba(218,218,218,1) 51%,rgba(178,176,176,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */\r\n");
      out.write("filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#eaeaea', endColorstr='#b2b0b0',GradientType=0 ); /* IE6-9 */\r\n");
      out.write("\r\n");
      out.write("\t#customheader h2{\r\n");
      out.write("\tcolor:black;\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#maincard{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\tpadding:0px;\r\n");
      out.write("\t\tbackground-color: #ffffff;\r\n");
      out.write("\t\ttop:-50px;\r\n");
      out.write("\t\tmargin-bottom: 10px;\r\n");
      out.write("\t\tmargin-top: 0px;\r\n");
      out.write("\t\theight:700px;\r\n");
      out.write("\t\tborder-radius: 3px;\r\n");
      out.write("\t   \r\n");
      out.write("\t\t-webkit-box-shadow: 0px 9px 24px 0px rgba(0,0,0,0.75);\r\n");
      out.write("\t\t-moz-box-shadow: 0px 9px 24px 0px rgba(0,0,0,0.75);\r\n");
      out.write("\t\tbox-shadow: 0px 9px 24px 0px rgba(0,0,0,0.75);\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#bPending{\r\n");
      out.write("position:relative;\r\n");
      out.write("top:80px;\r\n");
      out.write("left:17%;\r\n");
      out.write("-webkit-box-shadow: 0px 4px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("-moz-box-shadow: 0px 4px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("box-shadow: 0px 4px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("}\r\n");
      out.write("#bPending:hover{\r\n");
      out.write("\r\n");
      out.write("top:83px;\r\n");
      out.write("-webkit-box-shadow: 0px 1px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("-moz-box-shadow: 0px 1px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("box-shadow: 0px 1px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#bc{\r\n");
      out.write("position:relative;float:left;top:20px;left:30px;color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bc:hover{ color:green}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"main-wrapper\">\r\n");
      out.write("            <div class=\"app\" id=\"app\">\r\n");
      out.write("               \r\n");
      out.write("                <aside class=\"sidebar\">\r\n");
      out.write("\t\t\t\t<img id=\"bg\" src=\"assets/bg.jpg\">\r\n");
      out.write("                    <div class=\"sidebar-container\">\r\n");
      out.write("                        <div class=\"sidebar-header\">\r\n");
      out.write("                            <div class=\"brand\">\r\n");
      out.write("                                <div class=\"logo\"> <span class=\"l l1\"></span> <span class=\"l l2\"></span> <span class=\"l l3\"></span> <span class=\"l l4\"></span> <span class=\"l l5\"></span> </div> PAASCU </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <nav class=\"menu\">\r\n");
      out.write("                            <ul class=\"nav metismenu\" id=\"sidebar-menu\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"index.html\"> <i class=\"fa fa-home\"></i> Dashboard </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("                                    <a href=\"survey.jsp\"> <i class=\"fa fa-table\"></i> Survey Schedule </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("                                </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("                                    <a href=\"addsurvey.jsp\"> <i class=\"fa fa-pencil-square-o\"></i> Add New Survey </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"active open\">\r\n");
      out.write("                                <a href=\"#demo\" data-toggle=\"collapse\"> <i class=\"fa fa-file-text-o\"></i> Database <i class=\"fa arrow\"></i> </a>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <ul id=\"demo\" class=\"collapse\">\r\n");
      out.write("                                        <li > <a href=\"accreditors.html\">\r\n");
      out.write("    \t\t\t\t\t\t\t\tAccreditors\r\n");
      out.write("    \t\t\t\t\t\t\t</a> </li>\r\n");
      out.write("                                        <li> <a href=\"School Systems.html\">\r\n");
      out.write("    \t\t\t\t\t\t\t\tSchool System\r\n");
      out.write("    \t\t\t\t\t\t\t</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li class = \"active\" > <a href=\"schoolSystems.html\">\r\n");
      out.write("    \t\t\t\t\t\t\t                School Systems\r\n");
      out.write("    \t\t\t\t\t\t\t</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t <li> <a href=\"programs.html\">\r\n");
      out.write("    \t\t\t\t\t\t\t\tDisciplines </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("                                 \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"#demo3\" data-toggle=\"collapse\"> <i class=\"fa fa-bar-chart\"></i> Reports <i class=\"fa arrow\"></i> </a><ul id=\"demo3\" class=\"collapse\"><li> <a href=\"reportGA.html\">GA Awardees</a> </li><li> <a href=\"reportHistory.html\">History</a> </li></ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t  <a href=\"notifications.html\"> <i class=\"fa fa-bell-o\"></i> Notifications <p style=\"width:15px; height:17px;text-align:center; border-radius:10px; font-family: Verdana; font-size:10px;float:right; background-color:red; color:white;\">10</p></a> \r\n");
      out.write("\t\t\t\t\t\t\t\t </li>\r\n");
      out.write("                                \r\n");
      out.write("                               \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write(" \r\n");
      out.write("                    <footer class=\"sidebar-footer\">\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                </aside>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t<video poster=\"assets/banner.jpg\" id=\"bgvid\"  playsinline autoplay muted loop>\r\n");
      out.write("  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the \"Pause\" button  -->\r\n");
      out.write("\r\n");
      out.write("<source src=\"assets/vid.mp4\" type=\"video/mp4\">\r\n");
      out.write("</video>\r\n");
      out.write("</div>\r\n");
      out.write("            <div id=\"welcome\">\r\n");
      out.write("\t\t\t  <h1 class=\"title\"  >\r\n");
      out.write("\t\t\t\t\t\t\t<a style=\"color:white;\" href=\"javascript:history.back()\"><em class=\"fa fa-arrow-circle-left\"></em> Back </a> \r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t   <header class=\"header\" id=\"customheader\">\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                </header>\r\n");
      out.write("\t\t\t\t<article class=\"content grid-page\">\r\n");
      out.write("                    <div class=\"title-block\">\r\n");
      out.write("                        <h3 class=\"title\" style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:history.back()\"><em class=\"fa fa-arrow-circle-left\"></em> Back </a> \r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<section class=\"section\" style=\"position:relative;top:-150px;\">\r\n");
      out.write("                        <div class=\"row sameheight-container\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div class=\"card sameheight-item\">\r\n");
      out.write("                                    <div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section class=\"section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 ArrayList<ProgramSurvey> hist = (ArrayList<ProgramSurvey>)request.getAttribute("history"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 String instName = (String)request.getAttribute("programName"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h2 >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(instName );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("                                        <section class=\"section\">\r\n");
      out.write("\r\n");
      out.write("                                         \r\n");
      out.write("  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr><div class=\"row\" style=\"width:100%\">\r\n");
      out.write("                                                <table id=\"smarttable\" class=\"table table-striped table-bordered table-hover\" style =\"width:100%\" >\r\n");
      out.write("                                                    <thead>\r\n");
      out.write("                                                      <tr>\r\n");
      out.write("                                                            <th>Survey Date</th>\r\n");
      out.write("                                                            <th>Survey Type</th>\r\n");
      out.write("                                                            <th>Board Approval</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th width=\"20%\">Decision</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Expiry Date</th>\r\n");
      out.write("                                                           \r\n");
      out.write("                                                        </tr>\r\n");
      out.write("                                                    </thead>\r\n");
      out.write("                                                    <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
for(ProgramSurvey ps: hist){ 
      out.write("\r\n");
      out.write("                                                        <tr>\r\n");
      out.write("                                                            <td>");
      out.print(ps.getSurveyDate());
      out.write("</td>\r\n");
      out.write("                                                            <td>");
      out.print(ps.getSurveyType());
      out.write("</td>                                                           \r\n");
      out.write("                                                            <td>");
      out.print(ps.getDecisionDate());
      out.write("</td>\r\n");
      out.write("                                                            <td>");
      out.print(ps.getBoardDecision());
      out.write("</td>\r\n");
      out.write("                                                            <td>");
      out.print(ps.getValidThru());
      out.write("</td>\r\n");
      out.write("                                                        </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                                    </tbody>\r\n");
      out.write("                                                </table>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                        </section>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </section>\r\n");
      out.write("                <div class=\"sidebar-overlay\" id=\"sidebar-overlay\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t  <!-- EVENT MODAL -->\r\n");
      out.write("       \t<div id=\"surveyModal\" class=\"modal fade\">\r\n");
      out.write("    \t\t<div class=\"modal-dialog modal-lg\" style=\"width:70%;\">\r\n");
      out.write("        \t\t<div class=\"modal-content\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t\t<div class=\"modal-header\">\r\n");
      out.write("                \t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"><span aria-hidden=\"true\">×</span> <span class=\"sr-only\">close</span></button>\r\n");
      out.write("                \t\t<h4 id=\"modalTitle\" class=\"modal-title\"></h4>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\r\n");
      out.write("            \t\t<div id=\"modalBody\" class=\"modal-body\"></div>\r\n");
      out.write("            \t\t<div id=\"modalfooter\" class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"delButton\" type=\"button\" class=\"close\" data-dismiss=\"modal\" onclick=\"delayDelete(1,650)\"><em id=\"delIcon\" class=\"fa fa-trash-o\"></em></button>\r\n");
      out.write("                \t\r\n");
      out.write("           \t\t \t</div>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("             \r\n");
      out.write("        <!-- Reference block for JS -->\r\n");
      out.write("        <div class=\"ref\" id=\"ref\">\r\n");
      out.write("            <div class=\"color-primary\"></div>\r\n");
      out.write("            <div class=\"chart\">\r\n");
      out.write("                <div class=\"color-primary\"></div>\r\n");
      out.write("                <div class=\"color-secondary\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          \r\n");
      out.write("        <script src=\"js/app.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /institutionProgramProfile.jsp(75,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${programName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /institutionProgramProfile.jsp(78,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${programName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
