/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-07-30 10:13:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class schoolSystemProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1498989697559L));
    _jspx_dependants.put("jar:file:/C:/Users/Joanna%20Lau/Desktop/THESIS/paws/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/PAWS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("        <title> PAASCU - Accreditation Schedule Manager </title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\t\t  <!-- IMPORTS -->\r\n");
      out.write("    <script src='js/jquery.min.js'></script>\r\n");
      out.write("    <script src='js/jquery-ui.min.js'></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/vendor.css\">\r\n");
      out.write("    <link href='fullcalendar.css' rel='stylesheet' />\r\n");
      out.write("    <link href='calendar/fullcalendar.print.css' rel='stylesheet' media='print' />\r\n");
      out.write("\t<script src='calendar/lib/moment.min.js'></script>\r\n");
      out.write("\t<script src='calendar/fullcalendar.min.js'></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\" css/dataTables.bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write(" \t<link title=\"timeline-styles\" rel=\"stylesheet\" href=\"css/timeline.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- END IMPORTS -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t$('#smarttable').DataTable();\r\n");
      out.write("\t\t} );\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/app.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/vendor.css\">\r\n");
      out.write("        <!-- Theme initialization -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("     $('#smarttable').DataTable( {\r\n");
      out.write("        \"scrollX\": true\r\n");
      out.write("    } );\r\n");
      out.write("\r\n");
      out.write("    $('#smarttable').DataTable( {\r\n");
      out.write("\t\r\n");
      out.write("        initComplete: function () {\r\n");
      out.write("            this.api().columns().every( function () {\r\n");
      out.write("                var column = this;\r\n");
      out.write("                var select = $('<select><option value=\"\"></option></select>')\r\n");
      out.write("                    .appendTo( $(column.footer()).empty() )\r\n");
      out.write("                    .on( 'change', function () {\r\n");
      out.write("                        var val = $.fn.dataTable.util.escapeRegex(\r\n");
      out.write("                            $(this).val()\r\n");
      out.write("                        );\r\n");
      out.write(" \r\n");
      out.write("                        column\r\n");
      out.write("                            .search( val ? '^'+val+'$' : '', true, false )\r\n");
      out.write("                            .draw();\r\n");
      out.write("                    } );\r\n");
      out.write(" \r\n");
      out.write("                column.data().unique().sort().each( function ( d, j ) {\r\n");
      out.write("                    select.append( '<option value=\"'+d+'\">'+d+'</option>' )\r\n");
      out.write("                } );\r\n");
      out.write("            } );\r\n");
      out.write("        }\r\n");
      out.write("    } );\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#smarttable2').DataTable();\r\n");
      out.write("\t\t} );\r\n");
      out.write("$.fn.dataTable.ext.errMode = 'none';\r\n");
      out.write("\t\t\r\n");
      out.write("            var themeSettings = (localStorage.getItem('themeSettings')) ? JSON.parse(localStorage.getItem('themeSettings')) :\r\n");
      out.write("            {};\r\n");
      out.write("            var themeName = themeSettings.themeName || '';\r\n");
      out.write("            if (themeName)\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app-' + themeName + '.css\">');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                document.write('<link rel=\"stylesheet\" id=\"theme-style\" href=\"css/app.css\">');\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\tbody {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-family: \"Lucida Grande\",Helvetica,Arial,Verdana,sans-serif;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#calendar {\r\n");
      out.write("\t\tmax-width: 900px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t#bg{\r\n");
      out.write("\theight: 640px;\r\n");
      out.write("\tposition:fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#smarttable2{\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#smarttable th, #smarttable td {\t\t\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t\toverflow: hidden;\r\n");
      out.write("\t\ttext-overflow: ellipsis;\r\n");
      out.write("\t\twhite-space: nowrap;\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#smarttable th{\r\n");
      out.write("\t\tbackground-color:#85CE36; !important\r\n");
      out.write("\t\tcolor:#3c4731;\r\n");
      out.write("\t\tfont-size:110%;\t\t}\r\n");
      out.write("\r\n");
      out.write("\t#smarttable td{\r\n");
      out.write("\t\tpadding:15px;\r\n");
      out.write("\t\tpadding-left:10px;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\tcolor:#3c4731;\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t#smarttable tr:nth-child(even){\r\n");
      out.write("\t\tbackground-color:#e6f2da;}\r\n");
      out.write("\t\r\n");
      out.write("\t.container{\r\n");
      out.write("\t\twidth: 125%;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\theight: 130px;\r\n");
      out.write("\t\tz-index:-1;\r\n");
      out.write("\t\tmargin-left:-15px;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#smarttable tr:hover {\r\n");
      out.write("\t\tbackground: rgba(255,255,255,1);\r\n");
      out.write("\t\tbackground: -moz-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(255,255,255,1)), color-stop(47%, rgba(246,246,246,1)), color-stop(100%, rgba(237,237,237,1)));\r\n");
      out.write("\t\tbackground: -webkit-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: -o-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: -ms-linear-gradient(top, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tbackground: linear-gradient(to bottom, rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%);\r\n");
      out.write("\t\tfilter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ededed', GradientType=0 );\r\n");
      out.write("\r\n");
      out.write("\t\t-webkit-box-shadow: inset 0px 1px 5px 0px rgba(0,0,0,0.49);\r\n");
      out.write("\t\t-moz-box-shadow: inset 0px 1px 5px 0px rgba(0,0,0,0.49);\r\n");
      out.write("\t\tbox-shadow: inset 0px 1px 5px 0px rgba(0,0,0,0.49);\r\n");
      out.write("\t\tcursor: pointer;}\r\n");
      out.write("\t\t\r\n");
      out.write("\t#bPending{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("-webkit-box-shadow: 0px 4px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("-moz-box-shadow: 0px 4px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("box-shadow: 0px 4px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("}\r\n");
      out.write("#bPending:hover{\r\n");
      out.write("\r\n");
      out.write("top:3px;\r\n");
      out.write("-webkit-box-shadow: 0px 1px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("-moz-box-shadow: 0px 1px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("box-shadow: 0px 1px 7px 1px rgba(0,0,0,0.41);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"main-wrapper\">\r\n");
      out.write("            <div class=\"app\" id=\"app\">\r\n");
      out.write("                <header class=\"header\">\r\n");
      out.write("                    <div class=\"header-block header-block-collapse hidden-lg-up\"> <button class=\"collapse-btn\" id=\"sidebar-collapse-btn\">\r\n");
      out.write("    \t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("    \t\t</button> </div>\r\n");
      out.write("                  \r\n");
      out.write("\t\t\t\t    <div class=\"header-block header-block-search hidden-sm-down\">\r\n");
      out.write("                        <form role=\"search\">\r\n");
      out.write("                            <div class=\"input-container\"> <i class=\"fa fa-search\"></i> <input type=\"search\" placeholder=\"Search\">\r\n");
      out.write("                                <div class=\"underline\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                     \r\n");
      out.write("                    <div class=\"header-block header-block-nav\">\r\n");
      out.write("                        <ul class=\"nav-profile\">\r\n");
      out.write("                            <li class=\"notifications new\">\r\n");
      out.write("                                <a href=\"\" data-toggle=\"dropdown\"> <i class=\"fa fa-bell-o\"></i> <sup>\r\n");
      out.write("    \t\t\t      <span class=\"counter\">1</span>\r\n");
      out.write("    \t\t\t    </sup> </a>\r\n");
      out.write("                                <div class=\"dropdown-menu notifications-dropdown-menu\">\r\n");
      out.write("                                    <ul class=\"notifications-container\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"\" class=\"notification-item\">\r\n");
      out.write("                                                <div class=\"img-col\">\r\n");
      out.write("                                                    <div class=\"img\" style=\"background-image: url('assets/faces/marcos,nelson.jpg')\"></div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"body-col\">\r\n");
      out.write("                                                    <p> <span class=\"accent\">Marcos, Nelson Phd</span> Achievement: <span class=\"accent\">Completed 100th survey</span>. </p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                       \r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <footer>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li> <a href=\"\">\r\n");
      out.write("    \t\t\t            View All\r\n");
      out.write("    \t\t\t          </a> </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </footer>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </header>\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t<article class=\"content grid-page\">\r\n");
      out.write("                    <div class=\"title-block\">\r\n");
      out.write("                        <h3 class=\"title\" style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"SchoolSystems\"><em class=\"fa fa-arrow-circle-left\"></em> School Systems List </a> \r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"title\" style=\"float:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<em class=\"fa fa-pencil\"></em> Edit\r\n");
      out.write("                        </h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<section class=\"section\">\r\n");
      out.write("                        <div class=\"row sameheight-container\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div class=\"card sameheight-item\">\r\n");
      out.write("                                    <div class=\"card-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section class=\"section\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6> Date of Membership:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                        <section class=\"section\">\r\n");
      out.write("\r\n");
      out.write("                                         \r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                               \r\n");
      out.write("<!--                                                 <div class=\"col-md-12\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t<br> -->\r\n");
      out.write("<!--                                                     <button type=\"button\" style=\"float:right; width:260px;\"  class=\"btn btn-secondary btn-sm\" onclick=\"location.href='addProgram_sch.html';\"><em class=\"fa fa-plus\"></em>Add Institutions to this School System</button><br> -->\r\n");
      out.write("<!--                                                  </div> -->\r\n");
      out.write("                                            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                                <table id=\"smarttable\" class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("                                                    <thead>\r\n");
      out.write("                                                      <tr>\r\n");
      out.write("                                                            <th>Institution Name</th>\r\n");
      out.write("                                                            <th>Acronym</th>\r\n");
      out.write("                                                            <th>City</th>\r\n");
      out.write("                                                            <th>View Profile</th>\r\n");
      out.write("                                                           \r\n");
      out.write("                                                        </tr>\r\n");
      out.write("                                                    </thead>\r\n");
      out.write("                                                    <tbody>\r\n");
      out.write("                                                    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                                    </tbody>\r\n");
      out.write("                                                </table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                              \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                        </section>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </section>\r\n");
      out.write("                <div class=\"sidebar-overlay\" id=\"sidebar-overlay\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t  <!-- EVENT MODAL -->\r\n");
      out.write("       \t<div id=\"surveyModal\" class=\"modal fade\">\r\n");
      out.write("    \t\t<div class=\"modal-dialog modal-lg\" style=\"width:80%;\">\r\n");
      out.write("        \t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t  <table id=\"smarttable2\" class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("                                                    <thead>\r\n");
      out.write("                                                      <tr>\r\n");
      out.write("                                                            <th>Program Name</th>\r\n");
      out.write("                                                            <th>Survey Type</th>\r\n");
      out.write("                                                            <th>Star Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>End Date</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Board Approval Date</th>\r\n");
      out.write("                                                           \r\n");
      out.write("                                                        </tr>\r\n");
      out.write("                                                    </thead>\r\n");
      out.write("                                                    <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                                        <tr>\r\n");
      out.write("                                                            <td>Computer Science with specialization in Software Technology</td>\r\n");
      out.write("                                                            <td>Preliminary</td>\r\n");
      out.write("                                                            <td>September 21, 2000</td>\r\n");
      out.write("                                                            <td>September 22, 2000</td>\r\n");
      out.write("                                                            <td>November 11, 2000</td>\r\n");
      out.write("                                                            \r\n");
      out.write("                                                        </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                                    </tbody>\r\n");
      out.write("                                                </table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\t\t\t\t\r\n");
      out.write("             \r\n");
      out.write("        <!-- Reference block for JS -->\r\n");
      out.write("        <div class=\"ref\" id=\"ref\">\r\n");
      out.write("            <div class=\"color-primary\"></div>\r\n");
      out.write("            <div class=\"chart\">\r\n");
      out.write("                <div class=\"color-primary\"></div>\r\n");
      out.write("                <div class=\"color-secondary\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          \r\n");
      out.write("        <script src=\"js/app.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /schoolSystemProfile.jsp(255,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${schoolsystem.getName()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /schoolSystemProfile.jsp(258,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${schoolsystem.getDateJoined()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /schoolSystemProfile.jsp(294,14) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/schoolSystemProfile.jsp(294,14) '${institutions}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${institutions}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /schoolSystemProfile.jsp(294,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("inst");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td> ");
            if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td> ");
            if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td> ");
            if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"ViewInstitution?institutionID=");
            if (_jspx_meth_c_005fout_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\">View</a>\r\n");
            out.write('\r');
            out.write('\n');
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t        \t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /schoolSystemProfile.jsp(296,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inst.getName()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /schoolSystemProfile.jsp(298,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inst.getInstitutionAcronym()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /schoolSystemProfile.jsp(300,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inst.getCity()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /schoolSystemProfile.jsp(303,54) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inst.getInstitutionID()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }
}
